language: node_js 

node_js:
  - "stable"

services: mongodb

addons:
 apt:
   sources:
     - ubuntu-toolchain-r-test
   packages:
     - gcc-4.8
     - g++-4.8

cache:
  directories:
    - "node_modules"


before_script:
  - npm install

sudo: required


script:
  - npm test
  - npm run test
